<template>
    <transition name="fade">
        <div v-if="loading" class="loader-container" :class="absolute ? 'absolute' : 'fixed'">
            <div class="loadingio-spinner-ripple-5mcbhecjd4i"><div class="ldio-l6bkp3240qe">
            <div></div><div></div>
            </div></div>
        </div>
    </transition>
</template>






<script type="text/javascript">
/**
* ==================================================================================
* Loader for VUE components
*
* Required PROPS:
* - loading variable
*
* ==================================================================================
**/

export default {
    props: {
        loading: {
            default: false,
            type: Boolean,
        },

        absolute: {
            default: false,
            type: Boolean,
        },
    },
}
</script>

<style type="text/css" scoped>
/*
|-----------------------------------------------
| @Preloaders
|-----------------------------------------------
*/

/*
| @General
|-----------------------------------------------
*/
.fixed {
    position: fixed;
}

.absolute {
    position: absolute;
}

.loader-container {
    background-color: rgba(0, 0, 0, 0.3);
}

.loader-container, .loader {
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    margin: auto;
    z-index: 9999999;
}

.loader-container {
    height: 100%;
    width: 100%;
}

@keyframes ldio-l6bkp3240qe {
  0% {
    top: 38px;
    left: 38px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: -3px;
    left: -3px;
    width: 82px;
    height: 82px;
    opacity: 0;
  }
}.ldio-l6bkp3240qe div {
  position: absolute;
  border-width: 12px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-l6bkp3240qe 1.639344262295082s cubic-bezier(0,0.2,0.8,1) infinite;
}.ldio-l6bkp3240qe div:nth-child(1) {
  border-color: #93dbe9;
  animation-delay: 0s;
}
.ldio-l6bkp3240qe div:nth-child(2) {
  border-color: #689cc5;
  animation-delay: -0.819672131147541s;
}
.loadingio-spinner-ripple-5mcbhecjd4i {
  width: 78px;
  height: 78px;
  display: inline-block;
  overflow: hidden;
  background:none;
  top: 50%;
    left: 50%;
    transform: translate(-50% , -50%);
    position: absolute;
}
.ldio-l6bkp3240qe {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.78);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-l6bkp3240qe div { box-sizing: content-box; }
/* generated by https://loading.io/ */


</style>
